# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='vote_info',
            name='state',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
